version: '3.8'

networks:
 default:
  external:
    name: minio

# Settings and configurations that are common for all containers
x-minio-common: &minio-common
  image: quay.io/minio/minio:latest
  command: server --console-address ":9001" http://minio{1...4}/data{1...8}
  expose:
    - "9000"
    - "9001"
  environment:
    TZ: Asia/Shanghai
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: minioadmin
  healthcheck:
    test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
    interval: 30s
    timeout: 20s
    retries: 3

# starts 4 docker containers running minio server instances.
# using nginx reverse proxy, load balancing, you can access
# it through port 9000.
services:
  minio1:
    <<: *minio-common
    container_name: minio-1
    hostname: minio1
    volumes:
      - /opt/data/minio/minio-1/data-1:/data1
      - /opt/data/minio/minio-1/data-2:/data2
      - /opt/data/minio/minio-1/data-3:/data3
      - /opt/data/minio/minio-1/data-4:/data4
      - /opt/data/minio/minio-1/data-5:/data5
      - /opt/data/minio/minio-1/data-6:/data6
      - /opt/data/minio/minio-1/data-7:/data7
      - /opt/data/minio/minio-1/data-8:/data8

  minio2:
    <<: *minio-common
    container_name: minio-2
    hostname: minio2
    volumes:
      - /opt/data/minio/minio-2/data-1:/data1
      - /opt/data/minio/minio-2/data-2:/data2
      - /opt/data/minio/minio-2/data-3:/data3
      - /opt/data/minio/minio-2/data-4:/data4
      - /opt/data/minio/minio-2/data-5:/data5
      - /opt/data/minio/minio-2/data-6:/data6
      - /opt/data/minio/minio-2/data-7:/data7
      - /opt/data/minio/minio-2/data-8:/data8

  minio3:
    <<: *minio-common
    container_name: minio-3
    hostname: minio3
    volumes:
      - /opt/data/minio/minio-3/data-1:/data1
      - /opt/data/minio/minio-3/data-2:/data2
      - /opt/data/minio/minio-3/data-3:/data3
      - /opt/data/minio/minio-3/data-4:/data4
      - /opt/data/minio/minio-3/data-5:/data5
      - /opt/data/minio/minio-3/data-6:/data6
      - /opt/data/minio/minio-3/data-7:/data7
      - /opt/data/minio/minio-3/data-8:/data8

  minio4:
    <<: *minio-common
    container_name: minio-4
    hostname: minio4
    volumes:
      - /opt/data/minio/minio-4/data-1:/data1
      - /opt/data/minio/minio-4/data-2:/data2
      - /opt/data/minio/minio-4/data-3:/data3
      - /opt/data/minio/minio-4/data-4:/data4
      - /opt/data/minio/minio-4/data-5:/data5
      - /opt/data/minio/minio-4/data-6:/data6
      - /opt/data/minio/minio-4/data-7:/data7
      - /opt/data/minio/minio-4/data-8:/data8

  nginx:
    image: nginx:alpine
    container_name: minio-nginx
    hostname: nginx
    environment:
      TZ: Asia/Shanghai
    volumes:
      - /opt/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /opt/nginx/nginx.pid:/var/run/nginx.pid
      - /opt/nginx/logs:/var/log/nginx
    ports:
      - "9000:9000"
      - "9001:9001"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
